"""Created the new column-enspire

Revision ID: 04a6b4437938
Revises: f5d67799c8f3
Create Date: 2026-03-08 16:08:18.296069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04a6b4437938'
down_revision: Union[str, Sequence[str], None] = 'f5d67799c8f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('expires_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link', 'expires_at')
    # ### end Alembic commands ###
