"""Created users table and male foreign key, added user_id

Revision ID: d3bf2a4c4b5d
Revises: 05abef220728
Create Date: 2026-03-09 14:29:12.744296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3bf2a4c4b5d'
down_revision: Union[str, Sequence[str], None] = '05abef220728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'link', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'link', type_='foreignkey')
    op.drop_column('link', 'user_id')
    # ### end Alembic commands ###
