"""Rename tap_count to click_count

Revision ID: f5d67799c8f3
Revises: 072912603052
Create Date: 2026-03-08 15:30:05.930441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5d67799c8f3'
down_revision: Union[str, Sequence[str], None] = '072912603052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('click_count', sa.Integer(), nullable=True))
    op.drop_column('link', 'tap_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('tap_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('link', 'click_count')
    # ### end Alembic commands ###
